// react-app/src/todos/add-todo-form/add-todo-form.js
import React, { useContext, useState } from "react";
import { TodosContext } from "../state-store/todos";
import todoService from "../../service/todos";
import { statuses, priorities } from "../prototype";
import "./add-todo-form.css";

const AddTodoForm = () => {
  const { setLoading, setError, addTodo } = useContext(TodosContext);
  const [newTodo, setNewTodo] = useState({ task: "", priority: "Low", status: "uncompleted" });

  const handleChange = (e) => {
    setNewTodo({ ...newTodo, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    const todo = await todoService.create(newTodo);
    if (todo.error) setError(todo.error);
    else addTodo(todo);
    setLoading(false);
    e.target.reset();
  };

  return (
    <form onChange={handleChange} onSubmit={handleSubmit} className="add-todo-form">
      <div className="inputs-wrapper">
        <div className="input-field">
          <input type="text" name="task" required placeholder="Task" className="nf" />
        </div>

        <div className="input-field">
          <div className="select-wrapper">
            <label htmlFor="priority">Priority: </label>
            <select name="priority" defaultValue={priorities[0]} id="priority" className="nf">
              {priorities.map((status, i) => (
                <option defaultValue={i} key={i}>
                  {status}
                </option>
              ))}
            </select>
          </div>
          <div className="select-wrapper">
            <label htmlFor="status">Status: </label>
            <select name="status" defaultValue={statuses[0]} id="status" className="nf">
              {statuses.map((status, i) => (
                <option defaultValue={i} key={i}>
                  {status}
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      <button className="btn" type="submit">
        Add
      </button>
    </form>
  );
};

export default AddTodoForm;

// angular-app/src/app/todos/add-todo-form/add-todo-form.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: '[add-todo-form]',
  templateUrl: './add-todo-form.component.html',
  styleUrls: ['./add-todo-form.component.css']
})
export class AddTodoForm implements OnInit {
  priorities: string[] = ["Low", "Medium", "Heigh"];
  statuses: string[]  = ["Hold", "In Progress", "Completed"];

  constructor() { }

  ngOnInit(): void {
  }

  handleChange(e:any) {
    console.log(e.target.value);
  }
  
  handleSubmit(e: Event) {
    e.preventDefault();
    console.log(e);

  }

}

<form (change)="handleChange($event)" (submit)="handleSubmit($event)" class="add-todo-form">
  <div class="inputs-wrapper">
    <div class="input-field">
      <input type="text" name="task" required placeholder="Task" class="nf" />
    </div>

    <div class="input-field">
      <div class="select-wrapper">
        <label htmlFor="priority">Priority: </label>
        <select name="priority" id="priority" class="nf">
          <option *ngFor="let priority of priorities; index as i" [value]="i">
            {{priority}}
          </option>
        </select>
      </div>
      <div class="select-wrapper">
        <label htmlFor="status">Status: </label>
        <select name="status" id="status" class="nf">
          <option *ngFor="let status of statuses; index as i" [value]="i">
            {{status}}
          </option>
        </select>
      </div>
    </div>
  </div>

  <button class="btn" type="submit">
    Add
  </button>
</form>
