// react-app/src/layout/navbar/navbar.js
import React, { useState } from "react";
import { NavLink } from "react-router-dom";
import "./navbar.css";

function Navbar() {
  const [show, setShow] = useState(false);

  return (
    <div>
      {show && (
        <nav className="navbar" onClick={() => setShow(false)}>
          <NavLink to="/" className="nav-link">
            Tic Tac Toe
          </NavLink>
          <NavLink to="/todos" className="nav-link">
            Todos
          </NavLink>
        </nav>
      )}
      <button onClick={() => setShow(!show)} className={"nav-btn nf " + (show && "x")}>
        <div className="nav-btn-bar1"></div>
        <div className="nav-btn-bar2"></div>
        <div className="nav-btn-bar3"></div>
      </button>
    </div>
  );
}

export default Navbar;

// angular-app/src/app/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { Link } from '../interface';


@Component({
  selector: 'navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})

export class Navbar  {
  show: boolean = false;
  links: Link[]  = [{ path: "", text: "Tic Tac Toe" }, {path:"todos", text:"Todos"}];

  showNavbar() {
    this.show = !this.show;
  }

}

<div>
  <nav *ngIf="show" class="navbar">
    <a *ngFor="let link of links" routerLink="{{link.path}}" (click)="showNavbar()" class="nav-link">
      {{link.text}}
    </a>
  </nav>

  <button (click)="showNavbar()" class="nav-btn nf {{(show && 'x' )}}">
    <div class="nav-btn-bar1"></div>
    <div class="nav-btn-bar2"></div>
    <div class="nav-btn-bar3"></div>
  </button>
</div>
