// angular-app/src/app/todo/todo.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Todo } from "../interface";

@Component({
  selector: 'todo-list',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css']
})
export class TodoComponent implements OnInit {
  statuses: string[] = ["Hold", "In Progress", "Completed"];
priorities: string[] = ["Low", "Medium", "Heigh"];
  // @Input() todos:Todo[]
  constructor() { }

  ngOnInit(): void {


  }

}

<ul>
  <li *ngFor="let todo of todos" class="todo-item">
    <span class="item-priority"> {{todo.priority}}</span>
    <select name="status" id="status" class="item-status nf">
      <option *ngFor="let status of statuses; index as i" value="i" [selected]="'todo.status === i'">
        {{status}}
      </option>
    </select>
    <span class="item-date">{{new Date(todo.timestamp)}</span>
    <button type="button" onClick={onDelete} class="btn-delete nf">
      ×
    </button>
  </li>
</ul>

// react-app/src/todos/todo/todo.js
import React, { useContext, useState } from "react";
import { TodosContext } from "../state-store/todos";
import todoService from "../../service/todos";
import { statuses } from "../prototype";
import "./todo.css";

const Todo = ({ todo }) => {
  const { setLoading, setError, deleteTodo, dateFormat } = useContext(TodosContext);
  const [edit, setEdit] = useState(false);
  const [task, setTask] = useState(todo.task || "");

  const handleUpdate = async (e) => {
    e.preventDefault();
    setLoading(true);
    const newTodo = await todoService.update({ ...todo, task });
    if (newTodo.error) setError(newTodo.error);
    setEdit(false);
    setLoading(false);
  };

  const onDelete = async () => {
    setLoading(true);
    const result = await todoService.delete(todo.id);
    if (result.error) setError(result.error);
    else deleteTodo(todo);
    setLoading(false);
  };

  return (
    <li className="todo-item">
      <div className="item-task">
        {!edit ? (
          <span onClick={() => setEdit(true)}>{task}</span>
        ) : (
          <>
            <input defaultValue={task} onChange={(e) => setTask(e.target.value)} />
            <span onClick={handleUpdate} className="task-save">
              &#10004;
            </span>
          </>
        )}
      </div>

      <span className="item-priority"> {todo.priority}</span>
      <select name="status" defaultValue={todo.status} id="status" className="item-status nf">
        {statuses.map((status, i) => (
          <option defaultValue={i} key={i}>
            {status}
          </option>
        ))}
      </select>
      <span className="item-date">{new Date(todo.timestamp).toLocaleDateString("en-US", dateFormat)}</span>
      <button type="button" onClick={onDelete} className="btn-delete nf">
        ×
      </button>
    </li>
  );
};

export default Todo;
